stellar_models:
  O: [35000, 4.5, 0.0]
  B: [20000, 4.0, 0.0]
  A: [8500, 4.0, 0.0]
  F: [6500, 4.5, 0.0]
  G: [5800, 4.5, 0.0]
  K: [4000, 4.5, 0.0]
  M: [3000, 4.5, 0.0]

atomic_database:
  6562.8: "H-alfa (Balmer)"
  4861.3: "H-beta (Balmer)"
  4340.5: "H-gama (Balmer)"
  5892.9: "Na I (Sódio)"
  3968.5: "Ca II (Cálcio)"
  3933.7: "Ca II (Cálcio)"
  5172.7: "Mg I (Magnésio)"
  5270.3: "Fe I (Ferro)"
  8542.1: "Ca II (Infravermelho)"